# Generated by Django 5.2.8 on 2025-11-22 15:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('user_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('device_type', models.CharField(max_length=50)),
                ('browser', models.CharField(max_length=100)),
                ('os', models.CharField(max_length=100)),
                ('location', models.JSONField(null=True)),
                ('viewport', models.JSONField()),
                ('tags', models.JSONField(default=list)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('click', 'Click'), ('scroll', 'Scroll'), ('mouse_move', 'Mouse Move'), ('form_interaction', 'Form Interaction'), ('page_view', 'Page View'), ('custom', 'Custom Event')], max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('page_url', models.TextField()),
                ('data', models.JSONField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.session')),
            ],
            options={
                'indexes': [models.Index(fields=['session', 'timestamp'], name='events_even_session_bf2c44_idx'), models.Index(fields=['page_url', 'event_type'], name='events_even_page_ur_cde5b4_idx')],
            },
        ),
    ]
