# Generated by Django 5.2.8 on 2025-11-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('click', 'Click'), ('scroll', 'Scroll'), ('mouse_move', 'Mouse Move'), ('form_interaction', 'Form Interaction'), ('page_view', 'Page View'), ('custom', 'Custom Event'), ('rage_click', 'Rage Click'), ('error', 'Error')], max_length=50),
        ),
    ]
