# Generated by Django 5.2.8 on 2025-11-22 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeatmapData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.TextField()),
                ('heatmap_type', models.CharField(max_length=50)),
                ('device_type', models.CharField(max_length=50)),
                ('date_range_start', models.DateField()),
                ('date_range_end', models.DateField()),
                ('data', models.JSONField()),
                ('session_count', models.IntegerField()),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'unique_together': {('site', 'page_url', 'heatmap_type', 'device_type', 'date_range_start', 'date_range_end')},
            },
        ),
    ]
