# Generated by Django 5.2.8 on 2025-11-22 15:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('storage_url', models.URLField()),
                ('duration', models.IntegerField()),
                ('event_count', models.IntegerField(default=0)),
                ('has_errors', models.BooleanField(default=False)),
                ('has_rage_clicks', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.session')),
            ],
        ),
    ]
