# Generated by Django 5.2.8 on 2025-11-22 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_event_type'),
        ('recordings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recording',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='recording',
            name='storage_url',
        ),
        migrations.AddField(
            model_name='recording',
            name='recording_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='recording',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recording',
            name='recording_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='recording',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.session'),
        ),
    ]
