# Generated by Django 4.2.7 on 2025-11-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='is_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='site',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
